### ISSUE TITLE
Cannot read property 'split' of undefined.

### ISSUE THREAD

**Issue by agustif** [TedisAgolli/nextjs-routes-docs-generator#1]
Hi there, interesting idea, I tried to run it in my NextJS+TypeScript project but got this error.

Any idea on why it might be?
I though maybe because Im on unix/macOs filesystem, maybe?
`ERROR] Cannot read property 'split' of undefined`

**Comment by TedisAgolli** [comment]
Hey! Thanks for the nice words :) I have only tested it on Windows so it is possible. Split is used when trying to get the file name after "pages". It tries to convert 
```\pages\api\slapdash\hex-to-tailwind-command.js ``` to ```/api/hex-to-tailwind```

One thing I could think of is that you should make sure you're pointing at the base directory of your repo.
If there's any chance that the repo you're trying to use it on is public, I'd be happy to try to run it and debug the issue.
Otherwise, I'm definitely going to do some more testing on my side and see what could be wrong.

**Comment by agustif** [comment]
> Hey! Thanks for the nice words :) I have only tested it on Windows so it is possible. Split is used when trying to get the file name after "pages". It tries to convert 
> 
> ```\pages\api\slapdash\hex-to-tailwind-command.js ``` to ```/api/hex-to-tailwind```
> 
> 
> 
> One thing I could think of is that you should make sure you're pointing at the base directory of your repo.
> 
> If there's any chance that the repo you're trying to use it on is public, I'd be happy to try to run it and debug the issue.
> 
> Otherwise, I'm definitely going to do some more testing on my side and see what could be wrong.

Sorry but in this case that's not the case and the code is not public for now. But I do think the problem is my Osx system already provides a path without backslashes '//' like `'/pages/api/endpoint.ts'` will try a fix and send a PR that checks for presence of it before applying replace and so skipping it if no need?

Im thinking maybe you could try a similar enough *nix envirorment by using WSL in Windows maybe to be able to reproduce?

Thanks for the quick and welcoming response to my initial issue 🙏

**Comment by TedisAgolli** [comment]
WSL is a good idea. I'll try it out. Thanks for the help figuring out the issue!

**Comment by agustif** [comment]
Hey @TedisAgolli , glad you think so, maybe today I'll try to debug it myself with my windows machine which I never have an excuse to turn on anyways...

Will report any advances.
Have a nice sunday

**Comment by rubensflinco** [comment]
I made some corrections in the code and opened a pull request that should solve this type of problem, but I understood that it occurred because I understand that your api must have a condition to capture the endpoint method.

I'm still waiting for approval from the repository owner for this code update to be made available.

https://github.com/TedisAgolli/nextjs-routes-docs-generator/pull/2

**Comment by stoddabr** [comment]
There's probably more robust solutions but I think just changing the string replace line to this should fix things:
`        const path =
          "/" + file.replaceAll("/", "\\").split("\\pages\\")[1].split(".")[0].replaceAll("\\", "/");`

I opened a pull request: https://github.com/TedisAgolli/nextjs-routes-docs-generator/pull/3
